import 'package:flutter/material.dart';

const String kPoppins = 'Poppins';
const Color kBlack = Colors.black;
const Color kWhite = Colors.white;
const Color kMainAppColor = Color(0xff49C7F3);
const Color kCyan = Color(0xff007574);
const String kPublishablekey =
    'pk_test_51OvGjzBzmdWVZwGqFiK8MgmzsiLDQCGxGsVqCRxEi42uWnQBZleHflFHxHW61lwr0uPCtiLVOFbXE5P1xCQmpx4300adKVliU6';
const String kSecretkey =
    'sk_test_51OvGjzBzmdWVZwGq4wUefOWROeKMDNXPE2PqWNImhF2XYY9u0DFe48BnHgGCiwD84ZRLCMsHBDKCZn6HUtlwmiO300nSeSAw0t';
const String kAppLogo = 'assets/images/app_logo.webp';
const List<String> kSortedNeighborhoods = [
  'أبو قير',
  'أبو قير الجديدة',
  'أبيس',
  'الأزاريطة',
  'الإبراهيمية',
  'البيطاش',
  'الحضرة',
  'الحضرة الجديدة',
  'الدخيلة',
  'السرايا',
  'السيوف',
  'الشاطبي',
  'الصالحية',
  'الظاهرية',
  'العصافرة',
  'العطارين',
  'العوايد',
  'القباري',
  'الكافوري',
  'الكيلو 21',
  'اللبان',
  'المعمورة',
  'المكس',
  'المندرة',
  'المنشية',
  'المنشية البحرية',
  'الهانوفيل',
  'الورديان',
  'بحري',
  'بشاير الخير',
  'بولكلي',
  'جليم',
  'جناكليس',
  'حي أول العامرية',
  'حي أول المنتزة',
  'حي الجمرك',
  'حي العجمي',
  'حي بوكاليس',
  'حي ثان العامرية',
  'حي ثان المنتزة',
  'حي شرق',
  'حي غرب',
  'حي وسط',
  'رأس التين',
  'رشدي',
  'زيزينيا',
  'سابا باشا',
  'سان ستيفانو',
  'سبورتنج',
  'ستانلي',
  'سموحة',
  'سيدي بشر',
  'سيدي جابر',
  'سيدي كرير',
  'شدس',
  'صواري',
  'طوسون',
  'العامرية',
  'فلمنج',
  'فيكتوريا',
  'كامب شيزار',
  'كرموز',
  'كفر عبده',
  'كليوباترا',
  'كوم الدكة',
  'كينج مريوط',
  'لوران',
  'محرم بك',
  'محطة الرمل',
  'محطة قطار سيدي جابر',
  'مشارف العامرية الجديدة',
  'منشية النزهة',
  'ميامي',
  'ميدان الشهداء',
  'مينا البصل',
  'Agami',
  'Al-Ameriya',
  'Al-Asafra',
  'Al-Attarīn',
  'Al-Awaid',
  'Al-Azareeta',
  'Al-Betash',
  'Al-Dekhela',
  'Al-Gomrok District',
  'Al-Hadra',
  'Al-Ibrahimiyya',
  'Al-Kafouri',
  'Al-Luban',
  'Al-Maamoura',
  'Al-Mandara',
  'Al-Mansheya',
  'Al-Manshiya',
  'Al-Manshiya Al-Bahriya',
  'Al-Mex',
  'Al-Qabari',
  'Al-Salahiyya',
  'Al-Saraya',
  'Al-Shatbi',
  'Al-Siyouf',
  'Al-Wardyan',
  'Bakos',
  'Bahri',
  'Bashayer Al-Khayr',
  'Bolkly',
  'Camp Shizar',
  'Central District',
  'Cleopatra',
  'East District',
  'Fleming',
  'First Ameriya District',
  'First Montazah District',
  'Genaklis',
  'Gleem',
  'Kilometer 21',
  'Loran',
  'Martyrs Square',
  'Masharif Al-Ameriya Al-Jadida',
  'Miami',
  'Mina Al-Basal',
  'Moharam Bek',
  'New Al-Hadra',
  'Ras El-Teen',
  'Roushdy',
  'Saba Pasha',
  'San Stefano',
  'Sawari',
  'Second Ameriya District',
  'Second Montazah District',
  'Shiddas',
  'Sidi Bishr',
  'Sidi Gaber',
  'Sidi Gaber Train Station',
  'Sidi Krier',
  'Smouha',
  'Sporting',
  'Stanley',
  'Toson',
  'Victoria',
  'West District'
];
